const fs = require("fs");
const path = "D:/KiTerminal-UX/app/src/main/java/com/termux/app/compose/AndroidVmConfig.kt";
let raw = fs.readFileSync(path, "utf8");
let lines = raw.split(/\r?\n/);

// 替换 lines[378..447]（数组索引，L379-L448）：generateNativeDownloadScript 整个函数
// 先打印 L378-379 和 L447-449 确认边界
console.log("Boundary: 378:", JSON.stringify(lines[378]));
console.log("Boundary: 447:", JSON.stringify(lines[447]));
console.log("Boundary: 448:", JSON.stringify(lines[448]));
// 0-based: idx378 = line 379 start, idx447 = line 448 = "    }" end
let replacement = [];
replacement.push('    private fun generateNativeDownloadScript(): String {');
replacement.push('        val d = \'$\'');
replacement.push('        val sb = StringBuilder()');
replacement.push('        sb.append("echo \\"=== Android-x86 虚拟机 Phase 1: ISO 下载 (Termux 原生环境)\\"\\n")');
replacement.push('        sb.append("echo \\"Android $x86Version (API $apiLevel) / x86_64\\"\\n\\n")');
replacement.push('');
replacement.push('        // 1. 路径展开（vmDir 中可能包含字面量 ${d}HOME）');
replacement.push('        sb.append("# 路径展开\\n")');
replacement.push('        sb.append("_RAW_VM_DIR=\'").append(vmDir).append("\'\\n")');
replacement.push('        sb.append("eval VM_DIR=\\"${d}_RAW_VM_DIR\\"\\n")');
replacement.push('        sb.append("eval ISO_PATH=\\"$isoPath\\"\\n")');
replacement.push('        sb.append("mkdir -p \\"${d}VM_DIR\\"\\n")');
replacement.push('        sb.append("echo \\"  虚拟机目录: ${d}VM_DIR\\"\\n")');
replacement.push('        sb.append("echo \\"  ISO 目标 : ${d}ISO_PATH\\"\\n\\n")');
replacement.push('');
replacement.push('        // 2. 下载依赖（wget/curl）—— QEMU 依赖由 QemuVmConfig 后续处理');
replacement.push('        sb.append("# 下载依赖检查\\n")');
replacement.push('        sb.append("if ! command -v wget >/dev/null 2>&1 && ! command -v curl >/dev/null 2>&1; then\\n")');
replacement.push('            sb.append("    echo \\"安装 wget + ca-certificates...\\"\\n")');
replacement.push('            sb.append("    pkg update -y 2>/dev/null || true\\n")');
replacement.push('            sb.append("    pkg install -y wget ca-certificates || { echo \\"依赖安装失败\\"; exit 1; }\\n")');
replacement.push('        sb.append("fi\\n\\n")');
replacement.push('');
replacement.push('        // 3. 注入 bash 函数（下载 + ISO9660 校验）');
replacement.push('        sb.append(downloadWithFallbackFn())');
replacement.push('        sb.append(verifyIsoFn())');
replacement.push('');
replacement.push('        // 4. 诊断 + 决策 + 下载 + 二次校验');
replacement.push('        val urlArgs = isoUrls.joinToString(" ") { "\\"$it\\" }")');
replacement.push('        sb.append("echo \\"\\"\\n")');
replacement.push('        sb.append("echo \\"[诊断] 下载阶段变量：\\"\\n")');
replacement.push('        sb.append("echo \\"  ISO_PATH  = ${d}ISO_PATH\\"\\n")');
replacement.push('        sb.append("if [ -f \\"${d}ISO_PATH\\" ]; then\\n")');
replacement.push('            sb.append("    SZ=${d}(stat -c%s \\"${d}ISO_PATH\\" 2>/dev/null || echo 0)\\n")');
replacement.push('            sb.append("    echo \\"  ISO 存在 ? YES (${d}SZ bytes)\\"\\n")');
replacement.push('        sb.append("else echo \\"  ISO 存在 ? NO\\"\\n")');
replacement.push('        sb.append("fi\\n")');
replacement.push('        sb.append("echo \\"\\"\\n")');
replacement.push('');
replacement.push('        sb.append("ISO_MIN=52428800; NEED_DL=0\\n")');
replacement.push('        sb.append("echo \\"开始检查 ISO...\\"\\n")');
replacement.push('        sb.append("if [ ! -f \\"${d}ISO_PATH\\" ]; then\\n")');
replacement.push('            sb.append("    echo \\"  ISO 文件不存在，需要下载\\"; NEED_DL=1\\n")');
replacement.push('        sb.append("else\\n")');
replacement.push('            sb.append("    SZ=${d}(stat -c%s \\"${d}ISO_PATH\\" 2>/dev/null || echo 0)\\n")');
replacement.push('            sb.append("    echo \\"  ISO 文件存在 (${d}SZ bytes)，校验 ISO9660...\\"\\n")');
replacement.push('            sb.append("    if [ \\"${d}SZ\\" -lt \\"${d}ISO_MIN\\" ]; then\\n")');
replacement.push('                sb.append("        echo \\"    文件太小 (<50MB)，重新下载\\"\\n")');
replacement.push('                sb.append("        rm -f \\"${d}ISO_PATH\\"; NEED_DL=1\\n")');
replacement.push('            sb.append("    elif ! verify_iso_9660 \\"${d}ISO_PATH\\"; then\\n")');
replacement.push('                sb.append("        echo \\"    ISO9660 校验失败（镜像可能损坏），重新下载\\"\\n")');
replacement.push('                sb.append("        rm -f \\"${d}ISO_PATH\\"; NEED_DL=1\\n")');
replacement.push('            sb.append("    else echo \\"    ISO 校验通过 ✓\\"\\n")');
replacement.push('            sb.append("    fi\\n")');
replacement.push('        sb.append("fi\\n")');
replacement.push('        sb.append("echo \\"NEED_DL = ${d}NEED_DL\\"\\n")');
replacement.push('');
replacement.push('        sb.append("if [ \\"${d}NEED_DL\\" = \\"1\\" ]; then\\n")');
replacement.push('            sb.append("    echo \\"下载 $isoFileName (${isoUrls.size} 个镜像源)...\\"\\n")');
replacement.push('            sb.append("    download_with_fallback \\"${d}ISO_PATH\\" $urlArgs || {\\n")');
replacement.push('                sb.append("        echo \\"\\"\\n")');
replacement.push('                sb.append("        echo \\"所有镜像源均下载失败。请手动下载官方 ISO 放到:\\"\\n")');
replacement.push('                sb.append("        echo \\"  ${d}ISO_PATH\\"\\n")');
replacement.push('                sb.append("        sleep 5; exit 1\\n")');
replacement.push('            sb.append("    }\\n")');
replacement.push('            sb.append("    # 下载后二次校验\\n")');
replacement.push('            sb.append("    if ! verify_iso_9660 \\"${d}ISO_PATH\\"; then\\n")');
replacement.push('                sb.append("        echo \\"下载完成但 ISO9660 校验失败，删除坏镜像\\"; rm -f \\"${d}ISO_PATH\\"; exit 1\\n")');
replacement.push('            sb.append("    fi\\n")');
replacement.push('        sb.append("else\\n")');
replacement.push('            sb.append("    echo \\"Phase 1: ISO 就绪，跳过下载\\"\\n")');
replacement.push('        sb.append("fi\\n")');
replacement.push('        return sb.toString()');
replacement.push('    }');

const before = lines.slice(0, 378).join("\n");
const after = lines.slice(448).join("\n");
const final = before + "\n" + replacement.join("\n") + "\n" + after;
fs.writeFileSync(path, final, "utf8");
console.log("OK, lines:", final.split(/\r?\n/).length);
